### ISSUE TITLE
[Suggestion] Option to hide folders

### ISSUE THREAD

**Issue by Aluminite** [devkitPro/3ds-hbmenu#11]
This was one of the things I really liked about Gridlauncher.

Some homebrew (mainly BootNTR Selector) make folders in `sdmc:/3ds/`.

**Comment by ghost** [comment]
Yeah I really liked the "grid" aspect of it too.

**Comment by AnotherUser97** [comment]
Agreed. I do miss GridLauncher's UI...

**Comment by T3CHNOLOG1C** [comment]
I completely agree, we **need** an option to hide folders.

**Comment by fincs** [comment]
This will be implemented in the future.

**Comment by Derek1199** [comment]
It's been implemented lmao. I'll compile this sometime and take a look for fun xD

**Comment by ghost** [comment]
how is is implemented? i still can't find the option in the latest revision

**Comment by PseudoDistant** [comment]
I feel you should have the option to hide it _in the app..._
