### ISSUE TITLE
Exiting from a homebrew will return to the Home Menu

### ISSUE THREAD

**Issue by NexoCube** [devkitPro/3ds-hbmenu#14]
> while(aptMainLoop())
>     {
>         hidScanInput();
>         if(hidKeysDown() & KEY_START)
>             break;
> 
>         gfxFlushBuffers();
>         gfxSwapBuffers();
>         gspWaitForVBlank();
>     }
> 
>     aptExit();
>     nsExit();
>     gfxExit();
>     return 0;

This piece of code will return to the Home Menu, on smealum HBM, it returns to the HBMenu, and on this one it directly exits to the Home Menu :(

**Comment by NexoCube** [comment]
I'm so sorry, i didn't read correctly the README

**Comment by fincs** [comment]
You need to recompile your homebrew app using upstream libctru (a stable release will be rolled soon) for that to work with Rosalina (unrelated to new-hbmenu).

**Comment by NexoCube** [comment]
What do you mean by upstream ? My english is trash, i'm french lol

**Comment by fincs** [comment]
It means to grab the latest commit from the master branch: https://github.com/smealum/ctrulib

**Comment by NexoCube** [comment]
That's what i figured out, thanks, it's working :D
