### ISSUE TITLE
Using Hans

### ISSUE THREAD

**Issue by Levi86** [devkitPro/3ds-hbmenu#15]
Hi, I had hans in my apps list, but now it doesn't appear although the folder exist in the SD Caed, so my question is, how can I make it appear again? Thanks in advantage.

**Comment by fincs** [comment]
HANS is obsoleted by Luma3DS's built-in ExeFS/RomFS (LayeredFS) game patching feature and since it's not supported anyway with Rosalina, it was decided to hide it from view to remove confusion.
