### ISSUE TITLE
braindumper isn't working

### ISSUE THREAD

**Issue by Methallizer** [devkitPro/3ds-hbmenu#16]
The title. Everytime I try to launch it, it says that it isn't compatible.
P.S. Sorry for my bad English.

**Comment by fincs** [comment]
braindump is obsolete. You can use GodMode9 instead of braindump for dumping game assets.

**Comment by Methallizer** [comment]
@fincs How do you do then to extract an .cxi in GodMode9?

**Comment by fincs** [comment]
https://github.com/d0k3/GodMode9/blob/master/README.md
https://3ds.guide/godmode9-usage
