### ISSUE TITLE
[Suggestion] .firm application

### ISSUE THREAD

**Issue by david-zzj** [devkitPro/3ds-hbmenu#18]
the new-hbmenu is a very nice app.
i want to know can it be packed as an .firm file？eg：hbmenu.firm
so i can launch it through the Luma payloads when console power on .
THX.

**Comment by fincs** [comment]
This cannot be done. hbmenu and homebrew apps in general rely on Nintendo's 3DS OS to run. It is not possible to run any of this as a bare metal application.

I'm not sure if autobooting hbmenu-tid is feasible.
