### ISSUE TITLE
Request - Allow HBL Apps to be started from Sysnand

### ISSUE THREAD

**Issue by Lordkurzschluss** [devkitPro/3ds-hbmenu#20]
It would be nice to start HBL from sysnand
https://github.com/yellows8/hblauncher_loader/issues/82

**Comment by fincs** [comment]
What does this mean? You can already start hbmenu from sysnand by clicking on the appropriate tile on the Home Menu...

**Comment by astronautlevel2** [comment]
Do you mean loading 3dsx files from CTRNAND instead of SD card?

**Comment by fincs** [comment]
See AuroraWright/Luma3DS#861
