### ISSUE TITLE
New 2DS Home Button location

### ISSUE THREAD

**Issue by zoogie** [devkitPro/3ds-hbmenu#22]
![new2dshome](https://user-images.githubusercontent.com/28328903/28821433-fd196d6a-767a-11e7-9f6f-952d5e21e06b.png)

**Comment by fincs** [comment]
Heh, noted.

**Comment by GabrielRRussell** [comment]
Literally unplayable. Side note: Is it possible to detect model and do something like this?

**Comment by fincs** [comment]
[It is possible](https://github.com/smealum/ctrulib/blob/master/libctru/include/3ds/services/cfgu.h#L61). I just haven't had the time or willingness to fix it yet. (PRs accepted btw)
