### ISSUE TITLE
Hangs on homebrew launching

### ISSUE THREAD

**Issue by bronozoj** [devkitPro/3ds-hbmenu#23]
Using Rosalina menu to launch hbl.
Launching any 3dsx executables causes hangups
Luma3ds 8.1 (FW 11.5.0-38U)

**Comment by fincs** [comment]
Could you give me more details, such as hbmenu version, concrete application you're trying to run, etc?

**Comment by RibShark** [comment]
Happens to me too, on New3DS Luma3DS 8.1, running through Rosalina through hblauncher_loader injecting into H&S. I'm using the latest boot.3dsx on the Releases page. An example of an app that hangs is FBI, although all apps I have tried have hung in this way.

**Comment by fincs** [comment]
The H&S thing is not a hbmenu issue, it is a Rosalina issue.

**Comment by RibShark** [comment]
> The H&S thing is not a hbmenu issue, it is a Rosalina issue.

Ah, I see. That's a pity, I was hoping to not have to have any extra CIA files installed for a nice clean homemenu. I reckon that @bronozoj probably was launching hblauncher in the same way..

**Comment by bronozoj** [comment]
i have tried mostly injecting to h&s
but i tried launching using the hb launcher cia and tried injecting other apps too. to test whether its a problem with rosalina, i tried changing boot.3dsx to a different application, which produced no problems in the operation of various apps (fbi, dspdump).

**Comment by BlazeUchiha420** [comment]
I'm having an issue too. My apps were working fine before updating to Luma 9.0. I injected HB menu using rosalina and HB Menu launches just fine. When I try to launch any app through this method the HBL freezes. When I use the cia version, I'll try to boot up any of my apps, then my screen flashes red really quick then reboots to the HBL again. Also the cia version doesn't allow me to use the home button to exit to the home menu. CFW Luma3ds 9.0 OFW 11.6U. Nobody else seems to be having this problem. I tried replacing my homebrew apps and the boot.3dsx for this and still have the same issue. I reported this issue on the Luma github and they said it wasn't a Luma issue, but the problem didn't happen until I updated to Luma 9.0. Downgrading back to Luma 8.1.1 didn't work either. What could be causing this issue?

**Comment by FenrirWolf** [comment]
@BlazeUchiha420 My guess is that the non-injected HBL cia is not set as the homebrew target title in Rosalina. To fix that I would try opening the title, setting the current app as the homebrew launch target, then exiting back to the home menu. Things should work properly again when you run the title after that.

**Comment by fincs** [comment]
Closing, since it's not a hbmenu issue, it's a Rosalina issue. There's some rework that was done in a Luma3DS branch that might have fixed this.
