### ISSUE TITLE
Red Screen When Quitting Application! HELP

### ISSUE THREAD

**Issue by grabercn** [devkitPro/3ds-hbmenu#25]
when i quit an app it freezes at a red screen, is this fixable? i am using n3ds ver 11.5

**Comment by fincs** [comment]
What homebrew entrypoint are you using? What application crashes on exit? Could you give me more information about your system?

**Comment by grabercn** [comment]
I am using oot3d hax, I was using snes9x though it seems to do it for every app I've tried so far

**Comment by fincs** [comment]
It sounds like an issue with the hax 2.x payload (not a hbmenu issue). I'd advise you to head over to the [hax 2.x issue tracker](https://github.com/smealum/ninjhax2.x/issues).

**Comment by grabercn** [comment]
Thanks I will do that

**Comment by DumbJoe** [comment]
i thought yellow screen was an issue with payload....
