### ISSUE TITLE
Launcher Stuck

### ISSUE THREAD

**Issue by Maximumride1126** [devkitPro/3ds-hbmenu#34]
I installed this homebrew launcher and it has cause a major problem but no matter how many times i replace boot.3dsx it stays as the new hbmenu and not the old one and i would really like the old one back :(.

**Comment by fincs** [comment]
What "major" problem? Please keep in mind that the old version of hbmenu is of course an old version and it has missing support for e.g. Rosalina. It also runs twice as slow on old3ds.

**Comment by fincs** [comment]
¯\\\_(ツ)\_/¯
