### ISSUE TITLE
Text is too small in CHT devices

### ISSUE THREAD

**Issue by roytam1** [devkitPro/3ds-hbmenu#35]
CHT devices(Sell officially in Hong Kong and Taiwan) has smaller font size (20x24px) than others (25x30px) for more spaces to contain larger amount characters. (Source: converted bitmap from official cbf_zh-Hant-TW.bcfnt / cbf_std.bcfnt with ctr_FontConverter)

Possible solution to deal with such situation:
check width of "あ" with fontGetCharWidthInfo, CHT devices will return smaller value. Since ideograph is square, so normally width == height. (CHECK: does it return "24" in C/J/U/E? and does it return "19" in T?)
and then adjust scale factor before print.

Cross-post: 
https://github.com/BernardoGiordano/PKSM/issues/654
https://github.com/Steveice10/FBI/issues/423

![2018-01-08_23-53-39 846_top](https://user-images.githubusercontent.com/1192577/34678974-80926ca2-f48c-11e7-9980-e85214afac16.png)
![2018-01-08_23-53-39 846_bot](https://user-images.githubusercontent.com/1192577/34678979-845c96f0-f48c-11e7-99cd-033feddc569e.png)

**Comment by fincs** [comment]
Thank you for the report. I'll work on a fix.

I just have a question. Does the "あ" character exist in KOR/TWN system fonts as well? (I doubt so since that's hiragana "a", which is a Japanese character)

**Comment by roytam1** [comment]
> I just have a question. Does the "あ" character exist in KOR/TWN system fonts as well?

checked and it exists in all variants of default 3DS system font.

**Comment by fincs** [comment]
Perfect.

**Comment by fincs** [comment]
I've added some font scaling code, which should fix this problem. I've also realized that the traditional Chinese translation tends to overflow text boundaries, and some characters are missing altogether (with TWN font). If you are able to, could you send a PR fixing these issues?

**Comment by roytam1** [comment]
Fix confirmed! Thanks!
Font is now bigger! but it seem even bigger than in other devices?

![2018-01-14_08-28-58 035_top](https://user-images.githubusercontent.com/1192577/34911423-323b1006-f8c2-11e7-8c1d-2b69507ccd7f.png)
![2018-01-14_08-28-58 035_bot](https://user-images.githubusercontent.com/1192577/34911424-34bbfade-f8c2-11e7-857b-f2973c116421.png)

**Comment by roytam1** [comment]
It seems that baselinePos doesn't work as expected in T machines. While charWidth works as my expectation.

EDIT: maybe use glyphInfo->cellHeight? untested.
EDIT2: J/U/E cellHeight=30, cellWidth=24, T cellHeight=20, cellWidth=20
EDIT3: So by ratio, scaling by glyphWidth ratio gives better result.

J/U/E:
![j_top](https://user-images.githubusercontent.com/1192577/34913558-dc77e7ca-f8f8-11e7-9524-f6986c69ad90.png)

T:
![t_top](https://user-images.githubusercontent.com/1192577/34913560-dca3f892-f8f8-11e7-844a-5524ea5d8d8d.png)

**Comment by roytam1** [comment]
with modification:
````
        // Load the glyph texture sheets
        int i;
        TGLP_s* glyphInfo = fontGetGlyphInfo();
+       charWidthInfo_s* cwi = fontGetCharWidthInfo(fontGlyphIndexFromCodePoint(0x3042));
        s_glyphSheets = malloc(sizeof(C3D_Tex)*glyphInfo->nSheets);
-       s_textScale = 25.0f / glyphInfo->baselinePos;
+       s_textScale = 20.0f / (cwi->glyphWidth); // 20 is glyphWidth in J machines
        for (i = 0; i < glyphInfo->nSheets; i ++)
        {
                C3D_Tex* tex = &s_glyphSheets[i];

````

It shows same size:

J/U/E:
![j_atop](https://user-images.githubusercontent.com/1192577/34913706-cacc28b6-f8fc-11e7-9581-54cf5a55f20d.png)
![j_bot](https://user-images.githubusercontent.com/1192577/34913707-caf8783a-f8fc-11e7-8296-3781ba1c014a.png)

T:
![t_atop](https://user-images.githubusercontent.com/1192577/34913708-cb23f186-f8fc-11e7-9151-48e575abed69.png)
![t_bot](https://user-images.githubusercontent.com/1192577/34913709-cb4f0114-f8fc-11e7-8036-8b01ea1a4dd1.png)

**Comment by fincs** [comment]
I've tested your algorithm, and it results in correct font size for TWN and KOR, but small font size for CHN. Do you have any further suggestions?

**Comment by roytam1** [comment]
> I've tested your algorithm, and it results in correct font size for TWN and KOR, but small font size for CHN. Do you have any further suggestions?

Since I don't own CHN machine, I can't tell. 
whats inside cwi and glyphInfo struct in CHN machine?

**Comment by fincs** [comment]
Funnily enough, CHN metrics read: `glyphWidth: 20, charWidth: 24` (same as E/U/J font)

**EDIT**: I've done some measurements:

```c
int idx = fontGlyphIndexFromCodePoint(0x3042);
charWidthInfo_s* info = fontGetCharWidthInfo(idx);
FINF_s* fontInfo = fontGetInfo();
TGLP_s* glyphInfo = fontGetGlyphInfo();
sprintf(buf, "font(%dx%d) glyph(%dx%d) baseline(%d) maxWidth(%d)\ndefault(%d,%d) a(%d,%d)",
	fontInfo->width, fontInfo->height, glyphInfo->cellWidth, glyphInfo->cellHeight, glyphInfo->baselinePos, glyphInfo->maxCharWidth,
	fontInfo->defaultWidth.glyphWidth, fontInfo->defaultWidth.charWidth, info->glyphWidth, info->charWidth);
```

results in this:

EUR/USA/JPN:
```
font(25x30) glyph(24x30) baseline(25) maxWidth(24)
default(24,24) a(20,24)
```

CHN:
```
font(25x30) glyph(24x26) baseline(21) maxWidth(24)
default(24,24) a(20,24)
```

KOR:
```
font(25x30) glyph(24x26) baseline(21) maxWidth(24)
default(24,24) a(18,24)
```

TWN:
```
font(20x24) glyph(20x20) baseline(14) maxWidth(19)
default(20,20) a(14,19)
```

**Comment by roytam1** [comment]
> Funnily enough, CHN metrics read: glyphWidth: 20, charWidth: 24 (same as E/U/J font)

Then it show be shown as non-preScaled (i.e. like before the commit)
And from what I know is that, only TWN machines font have smaller font metrics due to file size limitation.

**Comment by fincs** [comment]
Looks like I have found a possible sweet spot:

```c
s_textScale = 30.0f / fontGetGlyphInfo()->cellHeight;
```

Can you confirm this gives desirable results on TWN?

**Comment by roytam1** [comment]
> s_textScale = 30.0f / fontGetGlyphInfo()->cellHeight;
> Can you confirm this gives desirable results on TWN?

It is a bit bigger than my mod, but still looks quite well.

![t_cw_atop](https://user-images.githubusercontent.com/1192577/34916432-4136b178-f930-11e7-8552-981cab9af36a.png)
![t_cw_bot](https://user-images.githubusercontent.com/1192577/34916433-41672bd2-f930-11e7-9fd6-e4101b76db54.png)

**Comment by fincs** [comment]
I'd say that looks nice as well. I'm commiting the fix.
https://github.com/fincs/new-hbmenu/commit/1197d56ea7d3cfa440abbabec7916c708b515238
