### ISSUE TITLE
[Request]: Launch new release 

### ISSUE THREAD

**Issue by BennyAlex** [devkitPro/3ds-hbmenu#37]
Hello,
could you please launch a new release with the latest commits?

**Comment by c-schuhmann** [comment]
I hope it's not too late and it can help you.
I've tested it on my own New3DS and it works nice. But I hope the devs publish a new official build soon!

[boot.zip](https://github.com/fincs/new-hbmenu/files/1864092/boot.zip)

**Comment by Multimegamander** [comment]
@BennyAlex I'm going to compile them until fincs starts again, go to my fork

**Comment by fincs** [comment]
Please don't promote unofficial builds. Locking thread as a result.

**Comment by fincs** [comment]
Also wrt OP: Yes, I'm aware there's been a long time since the last release. However, there are still things I need to do before a release, such as fixing #22 and porting over to citro2d.

**Comment by fincs** [comment]
Closed with 5a2a8db
