### ISSUE TITLE
An Exception Occured

### ISSUE THREAD

**Issue by ozomax1997** [devkitPro/3ds-hbmenu#39]
my 2ds is showing 

"An exception has occurred

Processor:                      ARM11 (core 0)
Exception type:             prefetch abort
Fault status:                  Translation - Section
Current Process:           menu (0004003000009802) "

if any further info is required i can add

**Comment by fincs** [comment]
How are you launching hbmenu? Since you are using Luma3DS, you should use Rosalina's 3dsx launching capabilities. *hax 2.x is unsupported by Luma3DS due to memory layout changes. (On the other hand, hbmenu still works perfectly under hax 2.x and original firmware).

**Comment by Demos25** [comment]
i'm using an old a9lh luma. what should I do?

**Comment by fincs** [comment]
You should upgrade to b9s and the latest version of Luma3DS (with Rosalina).
