### ISSUE TITLE
Hombrew via Rosalina menu on Download Play

### ISSUE THREAD

**Issue by ThatWeeb** [devkitPro/3ds-hbmenu#40]
So i was using the 3dsguide to try and homebrew the 3ds my friend gasve me. THe version being 7.1. I did all the steps and even retrace my steps and i keep on coming up with the same problem over and over again. WHenever i open the Download Play APplication and use the Rosaline Menu doing that hb thing it doesnt work. I close the software like it says, open it but it just shows a 3ds screen and thats it. nothing happens at all..... I have no idea what to do and it is giving me the bad case of throwing 3ds against wall syndrome.
![capture](https://user-images.githubusercontent.com/38641687/39106925-bc6dc09e-468c-11e8-9427-00e49b7d392d.PNG)

**Comment by urherenow** [comment]
1) Gitgub is NOT a support forum. Ask on Discord or GBAtemp

2) Try it using the latest FBI. If FBI works, install hblauncher_loader (and the .cia version of FBI, if you’re not opised ti having it on your home menu).

**Comment by Multimegamander** [comment]
Why tf do you have A9LH files when you're following a B9S guide?

**Comment by fincs** [comment]
Doesn't look like any other people are having problems with dlplay. They are, however, having problems with mset. In either case, it wouldn't really be an issue with hbmenu since hbmenu is just a shell on top of the 3dsx loading mechanism. If all, the issue would be in Rosalina, not in hbmenu.
