### ISSUE TITLE
Another thing...

### ISSUE THREAD

**Issue by distay0xGit** [devkitPro/3ds-hbmenu#43]
Is there any way to convert the PICA-compressed images.lz file to a format usable by GIMP or paint.net?

**Comment by fincs** [comment]
It's not PICA compressed. It's just GBA style lzss. Also, I plan at some unspecified point time to rewrite the graphical part of new-hbmenu with citro2d and tex3ds-based easily editable texture atlases.

**Comment by distay0xGit** [comment]
Okay. But what is the best font that matches the logo?

**Comment by fincs** [comment]
Unfortunately, I'm unable to answer that question. You might want to try locating the people who designed the hbmenu graphics (look in the README file).
