### ISSUE TITLE
Issue with compiling modified version.

### ISSUE THREAD

**Issue by distay0xGit** [devkitPro/3ds-hbmenu#44]
I made a specialized version of the source code that used the old HB v1.1 water, but the makefile always gets stuck on "regionfree.c". The constant result: "too few arguments to function 'FSUSER_OpenFileDirectly'". Is there a fix to this?

**Comment by fincs** [comment]
Uh, regionfree.c doesn't exist at all in hbmenu 2.x. Keep in mind that the old hbmenu codebase stopped being developed a long time ago.

**Comment by JG-GIT** [comment]
Re-open this issue. I'm experiencing another one. This error keeps and bricks the boot.3dsx from being built. "ld returned 1 exit status"
