### ISSUE TITLE
M O R E   C O D E   I S S U E S .

### ISSUE THREAD

**Issue by distay0xGit** [devkitPro/3ds-hbmenu#45]
I'm experiencing another issue. This error keeps the boot.3dsx from being built. "ld returned 1 exit status"

**Comment by fincs** [comment]
You gave almost no info about your development environment. Are you running latest tools and libs? If unsure, I recommend you follow [Setting up Development Environment](https://3dbrew.org/wiki/Setting_up_Development_Environment) from scratch.

By the way, this is **not** a support forum. This is an issue tracker, for tracking confirmed bugs and feature requests. We can have a talk if you want, we can be found idling on IRC; you can find us at EFnet #3dsdev (amongst other places).
