### ISSUE TITLE
Where is the lenny face!?!

### ISSUE THREAD

**Issue by CeeJayBeenz** [devkitPro/3ds-hbmenu#46]
How do I activate the lenny face logo to appear?

**Comment by fincs** [comment]
# ( ͡° ͜ʖ ͡°)

It's not that hard to figure it out ( ͡ᵔ ͜ʖ ͡ᵔ) You can look at the source code ( ͡⌐■ ͜ʖ ͡-■) If you can find the key combo the ( ͡° ͜ʖ ͡°) will come to you anytime ( ͡° ͜ʖ‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌├┬┴┬┴

**Comment by CeeJayBeenz** [comment]
Can you at least give me the name of the file that the code is in? I couldn't find anything in main.c.

**Comment by fincs** [comment]
Unfortunately giving out the name of the source code file would spoil the fun to people trying to find this secret functionality. However you can try to solve this challenge:

a7 6f 75 ( ͡° ͜ʖ ͡°) a7 30 32 ( ͡° ͜ʖ ͡°) 63 72 1c ( ͡° ͜ʖ ͡°) 63 65 ae ( ͡° ͜ʖ ͡°) 2f 68 1a ( ͡° ͜ʖ ͡°) a7 3f 75 ( ͡° ͜ʖ ͡°) a3 30 e1 2e

(hints: https://paulschou.com/tools/xlate/ https://rot13.com/)

**Comment by CeeJayBeenz** [comment]
�ou�02crce�/h�?u�0�. What's this?

**Comment by CeeJayBeenz** [comment]
70u, pzAy... K ?H?ADK... How do I do this!?! Aaaargh!

**Comment by fincs** [comment]
TWF5YmUgdGhpcyBpcyBhIGJldHRlciBoaW50ICggzaHCsCDNnMqWIM2hwrAp

**Comment by CeeJayBeenz** [comment]
ah yes, this is a better hint. but i'm still confused cause i am u n i n t e l l i g e n t.

**Comment by CeeJayBeenz** [comment]
I am so stupid literally all I have is n7 6s 75 n7 30 32 63 72 1p 63 65 nr 2s 68 1n n7 3s 75 n3 30 r1 2r.

**Comment by CeeJayBeenz** [comment]
i8cant8do8this8shit

**Comment by CeeJayBeenz** [comment]
uyhgsefyhugiwefijwefcuhiyervwchiuwerfvyuhigrvweyuhgwtvuryyugrtfhyetyjtyj

**Comment by CeeJayBeenz** [comment]
Giberish text. What is this?

**Comment by CeeJayBeenz** [comment]
ples halp

**Comment by fincs** [comment]
One of the boxes in the 'xlate' website can decode that. If you manage to find that box, maybe you can imagine new ways to decode my original hint ( ͡° ͜ʖ ͡°)

**Comment by CeeJayBeenz** [comment]
i hate everything aaaaaAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by CeeJayBeenz** [comment]
Can I please just have the code for activating the lenny face?

**Comment by MathPie** [comment]
TWF5YmUgdGhpcyBpcyBhIGJldHRlciBoaW50ICggzaHCsCDNnMqWIM2hwrAp
is a base64 code. It says "Maybe this is a better hint ( ͡° ͜ʖ ͡°)". This was too easy.
BUT.
a7 6f 75 ( ͡° ͜ʖ ͡°) a7 30 32 ( ͡° ͜ʖ ͡°) 63 72 1c ( ͡° ͜ʖ ͡°) 63 65 ae ( ͡° ͜ʖ ͡°) 2f 68 1a ( ͡° ͜ʖ ͡°) a7 3f 75 ( ͡° ͜ʖ ͡°) a3 30 e1 2e
looks like a hexadecimal code with rot* if you remove the "lenny" faces.... Interesting. Maybe not that interesting, but interesting.

**Comment by ThatNerdyPikachu** [comment]
https://github.com/fincs/new-hbmenu/blob/de4e3e0da0c0886db11f0396e5011d19d6ffa082/source/ui/background.c#L86

Someone test this

**Comment by stampylongr** [comment]
> https://github.com/fincs/new-hbmenu/blob/de4e3e0da0c0886db11f0396e5011d19d6ffa082/source/ui/background.c#L86
> Someone test this

@ThatNerdyPikachu That's just the Konami code with "B A Start" replaced with "Select"
Still may be something, though. I don't want to add CFW to my N2DS XL, I only now got homebrew to run in userland (after months of trying (maybe i'm just terrible at adding homebrew, who knows?)).
Someone else will have to do it.

**Comment by stampylongr** [comment]
> >https://github.com/fincs/new-hbmenu/blob/de4e3e0da0c0886db11f0396e5011d19d6ffa082/source/ui/background.c#L86 
> > Someone test this
> 
> That's just the Konami code with "B A Start" replaced with "Select"
> Still may be something, though. I don't want to add CFW to my N2DS XL, I only now got homebrew to run in userland (after months of trying (maybe i'm just terrible at adding homebrew, who knows?)).
> Someone else will have to do it.

@ThatNerdyPikachu Misread README, thought this was Rosalina. I just tried this, and nothing happened. Though we can search for something regarding [logo2.png](https://github.com/fincs/new-hbmenu/blob/master/gfx/logo2.png).
