### ISSUE TITLE
(Suggestion) Holding Up or Down buttons should scroll the list automatically

### ISSUE THREAD

**Issue by PolarisBeaver** [devkitPro/3ds-hbmenu#5]
Title is self explanatory, it's just a basic request. Some people may have a lot of items in their list and need to get to the bottom. It would take forever mashing the down button over and over again.

The interface is really smooth and responsive otherwise, great work!

**Comment by fincs** [comment]
You can use Left/Right to scroll faster, just like in the original hbmenu.

**Comment by DumbJoe** [comment]
> 
> 
> You can use Left/Right to scroll faster, just like in the original hbmenu.

...yeah but you still need to mash it to get to the bottom of a long list.....
