### ISSUE TITLE
Compiling with new tools

### ISSUE THREAD

**Issue by urherenow** [devkitPro/3ds-hbmenu#53]
I just installed a brand-new VM of Ubuntu, and all dkp tools and libraries (including build-essential). I get the following error when attempting to build new-hbmenu:

/home/urherenow/projects/new-hbmenu/source/menu-list.c:105:48: warning: dereferencing 'void *' pointer
   sdmc_dir_t* dirSt = (sdmc_dir_t*)dir->dirData->dirStruct;
                                                ^~
/home/urherenow/projects/new-hbmenu/source/menu-list.c:105:48: error: request for member 'dirStruct' in something not a structure or union
make[1]: *** [/opt/devkitpro/devkitARM/base_rules:85: menu-list.o] Error 1
make: *** [Makefile:174: all] Error 2

EDIT: Ok, the issue happened as a result of the new devkitARM. Just built this on a working VM, did a dkp-pacman -Syuu, which appeared to only update devkitARM, and it produces this same error now.

**Comment by fincs** [comment]
Thank you for reporting. This has been fixed with dkA r50-3.
