### ISSUE TITLE
Greenscreen after Flipnote Directions

### ISSUE THREAD

**Issue by ChaoticShadows** [devkitPro/3ds-hbmenu#58]
After I do the Flipnote Directions to install Boot9strap, a light green screen appears and everything freezes, can someone please help me.

**Comment by ChaoticShadows** [comment]
Ok, it turns out that boot.nds was missing on the root

**Comment by Oreo639** [comment]
This isn't tech support. This is for reporting bugs in homebrew menu's code (or feature requests). If you need tech support, ask on the Nintendo Homebrew discord.
