### ISSUE TITLE
building breaks on latest libctru commits

### ISSUE THREAD

**Issue by urherenow** [devkitPro/3ds-hbmenu#59]
As the title says. Updated libctru to build latest Luma3ds, now new-hbmenu doesn't build.

**Comment by fincs** [comment]
This is known and will be fixed at some point. Also please stick to stable releases, because stuff like this is avoided.

**Comment by fincs** [comment]
Fixed by fed35483f3ab97e87105d1fb0c9e14abdc5336bf
