### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by m1guelpf** [devkitPro/3ds-hbmenu#6]
Would be nice to have some screenshots in the readme...

**Comment by GabrielRRussell** [comment]
To show it off? It's nearly identical to the original HBL. It has a prettier background, and some more text.

(Also a settings tab I can't seem to open it just scrolls to the bottom)

**Comment by fincs** [comment]
Settings tab: see #8. (I.e. not implemented)
Otherwise this is a really minor cosmetic thing in the repo that doesn't entail any issue with the application itself.
