### ISSUE TITLE
The configuration button does not work

### ISSUE THREAD

**Issue by wuniversales** [devkitPro/3ds-hbmenu#63]
When you press the configuration button, all it does is scroll apps up.
Does not open any configuration menu.

How strange that all this time no one has reported it ...

My version:
Hombrew channel v2.1.0

**Comment by bfoos** [comment]
It's actually been reported a few times over the years. Here's an issue from 2017 that contains an explanation from @fincs 
https://github.com/fincs/new-hbmenu/issues/8

**Comment by Jaffacakelover** [comment]
So there isn't a CFW specific build, or a way for the app to detect how it's running, that can hide the button?
And it's a 'settings' logo, when its actual function is 'reboot'?

**Comment by fincs** [comment]
Reposting my comment from the old issue:

> Currently there's no actual settings page implemented (in the future there will be). On older entrypoints (ninjhax 1.x/hax 2.x) pressing it will display the reboot screen. On Rosalina it shows a small indicator reminding you that you can press the HOME button to go back to the HOME menu.

**Comment by Jaffacakelover** [comment]
Can the button not be removed then? Or when will functionality be added?

**Comment by fincs** [comment]
I cannot provide an estimate on when the configuration button will open a configuration menu, sorry.
