### ISSUE TITLE
[Request] Rescan ./3ds

### ISSUE THREAD

**Issue by eip618** [devkitPro/3ds-hbmenu#68]
Hello,

The hbmenu already seems to support surprise SD removal without crashing (unlike the actual OS) which is nice, however the SD is not scanned for new content or entries when the card is put back in.

How difficult/possible would this be to implement?

Edit: Maybe linked to a button command, maybe if the SD is reinserted? I don't know what the best implementation would be.

**Comment by fincs** [comment]
The readme clearly states that this is not the case, and for a very good reason:

> You should not hotswap the SD card while hbmenu is running since it compromises the 3DS OS's stability amongst other things. It is recommended that you instead use a file transfer homebrew application such as ftpd to transfer files without rebooting.
