### ISSUE TITLE
Stuck on Fetching latest hourly

### ISSUE THREAD

**Issue by yergerb** [devkitPro/3ds-hbmenu#70]
using new 3ds xl just keep saying fetching latest hourly doesn't do anything after force reboot and its the same thing. I've manually updated to the latest version of luma

**Comment by fincs** [comment]
It looks to me like you're posting this issue on the wrong repo. This is just the 3DS homebrew menu.

(Also fwiw we don't recommend using Luma auto-updaters or "nightly" builds of Luma since they are known to cause issues & support headaches).
