### ISSUE TITLE
Weird question

### ISSUE THREAD

**Issue by FieryMewtwo** [devkitPro/3ds-hbmenu#75]
So I'm very new to homebrew, and don't have CFW(using old-browserhax-xl on my launch model 3DS). I saw a version of
the old hbmenu with a grid UI(gridlauncher) and was wondering if I could use that.

**Comment by fincs** [comment]
No. That's an ancient fork of the *old* version of hbmenu, which is not supported anymore.

It is highly recommended to install and use [Luma3DS](https://github.com/LumaTeam/Luma3DS) (specifically Rosalina 3DSX loading support) for running homebrew as of 2021. Support for the old hax 2.x entrypoints is deprecated and is being considered for removal.

**Comment by FieryMewtwo** [comment]
Ah okay. The only reason I didn't do CFW was because I'm a wuss and I'm afraid I'll mess something up

**Comment by FieryMewtwo** [comment]
Thank you!
