### ISSUE TITLE
The v2.3.0 boot.3dsx binary is the same as the v2.2.0 boot.3dsx binary

### ISSUE THREAD

**Issue by grimson73** [devkitPro/3ds-hbmenu#79]
Name: boot.3dsx
Size: 361820 bytes (353 KiB)
SHA256: debb8d3ea476e7dcbc85b6f364ad8af575fb53c7032cd3ec2509011ecf6b4cd2

**Comment by Epicpkmn11** [comment]
This appears to no longer be the case:

    debb8d3ea476e7dcbc85b6f364ad8af575fb53c7032cd3ec2509011ecf6b4cd2  boot-v2.2.0.3dsx
    38ad2f360c6d4daba4730c6c46db1928bfdbe368d0295539c50ebcbbd658b703  boot-v2.3.0.3dsx

From the GitHub API it looks like the release binary was updated around half an hour after this issue was made.
