### ISSUE TITLE
Can't open settings

### ISSUE THREAD

**Issue by nickilicious** [devkitPro/3ds-hbmenu#8]
Pressing the settings icon doesn't do anything..

**Comment by fincs** [comment]
Currently there's no actual settings page implemented (in the future there will be). On older entrypoints (ninjhax 1.x/hax 2.x) pressing it will display the reboot screen. On Rosalina it shows a small indicator reminding you that you can press the HOME button to go back to the HOME menu.

**Comment by DumbJoe** [comment]
....could those settings be what the menuhax_manager v3.2 and chmm2 already does but doesn't work, or at least for me that are already provided in the starter kit, assuming you've finally implemented it?
