### ISSUE TITLE
Changing hbmenu desgin back to the original

### ISSUE THREAD

**Issue by iCRON862** [devkitPro/3ds-hbmenu#83]
I have a feature request to add an option or setting to switch between the new and old (original) desgin of the hbmenu if it's possible. Or how to rebuild the source code to switch the theme back to the original hbmenu desgin that will works on rosalina too? Sry, but you just completely ruined the hbmenu for me with the current design. I'm still using the v1.x from hbmenu.

**Comment by Masamune3210** [comment]
The old design would likely have to be redone from the ground up with the new setup. The whole reason the hbmenu had to be updated was moving to a newer way of handling things

**Comment by WinterMute** [comment]
There is no old design though, the update was primarily functional - moving to gpu rendering and adding shortcuts for instance. We have no idea what the old design might be.

**Comment by Masamune3210** [comment]
My guess is they are talking about the old software compositing, mostly the fact that it was less busy. Honestly don't know, only person who could elaborate would be OP
