### ISSUE TITLE
Konami Code Missing/Broken

### ISSUE THREAD

**Issue by gudenau** [devkitPro/3ds-hbmenu#9]
This lacks the Konami Code that the original had. When entered it changed the colors of the application.

**Comment by fincs** [comment]
There is still a secret code, however it has been slightly changed since the B and A buttons actually perform actions in new-hbmenu. Also the effect is different now.

**Comment by gudenau** [comment]
Nice Lenny.

**Comment by NinjaBoyLao** [comment]
If anyone else comes looking for this, like I did, he changed the original name of the constant, and searching "secret" won't bring anything up. Recommend looking in background.c and poking around there ;)

**Comment by fincs** [comment]
Shhhhhhhhh ( ͡° ͜ʖ ͡°)
