### ISSUE TITLE
I don't know how to install this

### ISSUE THREAD

**Issue by ghost** [devkitPro/3ds-hbmenu#90]
I have no clue how to install Homebrew. I have a 2DS XL, a HP Laptop 15-ef0xxx, and I don't know what I'm supposed to do or what I'm doing wrong. Please help!
(P.S. the laptop runs on Windows 10)

**Comment by urherenow** [comment]
Github is not a help forum.

https://3ds.hacks.guide/

**Comment by ghost** [comment]
nevermind i'll find out some day
