### ISSUE TITLE
Not building in Linux since Makefile update

### ISSUE THREAD

**Issue by Anonymous941** [devkitPro/3ds-hbmenu#93]
## Bug Report

The software does not compile.

### What's the issue you encountered?

I am trying to compile in Linux and got this error:

```bash
make[1]: *** No rule to make target 'program.shbin.o', needed by '/.../3ds-hbmenu/boot.elf'.  Stop.
make: *** [Makefile:179: all] Error 2
```

~~After running `git bisect`, I found the commit that introduced this error: 529597094b72e0a8870acb785c58878ded6793a4.~~ Edit: this also appears before this commit if I edit an image.

Obviously an error this big would have been caught if it were more widespread, so somehow it must be related to my computer.

### How can the issue be reproduced?

Run `make`.

### Environment

Ubuntu 23.10, no self-compiled libraries

**Comment by WinterMute** [comment]
I can't reproduce this at all.

How did you install devkitARM & the supplementary files? Have you modfied your installation in any way?

**Comment by Anonymous941** [comment]
It's working on another computer, so there must be some issue with my installation (even though I don't remember modifying anything).  Sorry to waste your time...
